"""add_chunk_fields_to_cv_embeddings

Revision ID: b6e2bb8ff282
Revises: 2cf0a8d5e5c3
Create Date: 2026-02-14 19:14:45.998915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e2bb8ff282'
down_revision: Union[str, Sequence[str], None] = '2cf0a8d5e5c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv_embeddings', sa.Column('chunk_text', sa.Text(), nullable=True))
    op.add_column('cv_embeddings', sa.Column('chunk_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cv_embeddings', 'chunk_index')
    op.drop_column('cv_embeddings', 'chunk_text')
    # ### end Alembic commands ###
