"""add_byok_smtp_twilio_fields

Revision ID: f03233686b7b
Revises: b6e2bb8ff282
Create Date: 2026-02-16 11:21:47.770924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f03233686b7b'
down_revision: Union[str, Sequence[str], None] = 'b6e2bb8ff282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_settings', sa.Column('smtp_host', sa.Text(), nullable=True, comment='SMTP server hostname (encrypted)'))
    op.add_column('notification_settings', sa.Column('smtp_port', sa.Integer(), nullable=True, comment='SMTP server port'))
    op.add_column('notification_settings', sa.Column('smtp_username', sa.Text(), nullable=True, comment='SMTP username (encrypted)'))
    op.add_column('notification_settings', sa.Column('smtp_password', sa.Text(), nullable=True, comment='SMTP password (encrypted)'))
    op.add_column('notification_settings', sa.Column('smtp_from_email', sa.Text(), nullable=True, comment='Sender email address (encrypted)'))
    op.add_column('notification_settings', sa.Column('smtp_from_name', sa.String(length=100), nullable=True, comment='Sender display name'))
    op.add_column('notification_settings', sa.Column('smtp_use_tls', sa.Boolean(), nullable=False, server_default='true', comment='Whether to use STARTTLS'))
    op.add_column('notification_settings', sa.Column('twilio_account_sid', sa.Text(), nullable=True, comment='Twilio account SID (encrypted)'))
    op.add_column('notification_settings', sa.Column('twilio_auth_token', sa.Text(), nullable=True, comment='Twilio auth token (encrypted)'))
    op.add_column('notification_settings', sa.Column('twilio_whatsapp_from', sa.Text(), nullable=True, comment='WhatsApp sender number (encrypted)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_settings', 'twilio_whatsapp_from')
    op.drop_column('notification_settings', 'twilio_auth_token')
    op.drop_column('notification_settings', 'twilio_account_sid')
    op.drop_column('notification_settings', 'smtp_use_tls')
    op.drop_column('notification_settings', 'smtp_from_name')
    op.drop_column('notification_settings', 'smtp_from_email')
    op.drop_column('notification_settings', 'smtp_password')
    op.drop_column('notification_settings', 'smtp_username')
    op.drop_column('notification_settings', 'smtp_port')
    op.drop_column('notification_settings', 'smtp_host')
    # ### end Alembic commands ###
